name: build-macos-arm64

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0-rc.1'
          check-latest: true

      - name: Set environment variables
        shell: bash
        run: |
          echo 'GOTAGS=cmount' >> $GITHUB_ENV
          echo 'BUILD_FLAGS=-include "^darwin/arm64" -cgo -macos-arch arm64 -cgo-cflags=-I/usr/local/include -cgo-ldflags=-L/usr/local/lib' >> $GITHUB_ENV

      - name: Install Libraries on macOS
        shell: bash
        run: |
          unset HOMEBREW_NO_INSTALL_FROM_API
          brew untap --force homebrew/core
          brew untap --force homebrew/cask
          brew update
          brew install --cask macfuse
          brew install git-annex git-annex-remote-rclone

      - name: Build rclone
        shell: bash
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rclone-macos-arm64
          path: rclone
